import { Suspense } from "react";
import { useRoutes, Routes, Route } from "react-router-dom";
import Home from "./components/home";

function App() {
  // Handle tempo routes dynamically
  let tempoRoutes = null;
  try {
    if (import.meta.env.VITE_TEMPO === "true") {
      // @ts-ignore - tempo-routes is generated by the tempo plugin
      const routes = require("tempo-routes").default;
      tempoRoutes = useRoutes(routes);
    }
  } catch (error) {
    // Tempo routes not available, continue without them
    console.log("Tempo routes not available");
  }

  return (
    <Suspense fallback={<p>Loading...</p>}>
      <>
        <Routes>
          <Route path="/" element={<Home />} />
        </Routes>
        {tempoRoutes}
      </>
    </Suspense>
  );
}

export default App;